import streamlit as st

st.title("ℹ️ About & Legal")

st.markdown("""
ClimateLens is an open-source research platform that explores climate-related
emotions and conversations through computational social science and natural
language processing (NLP).

The project aims to help researchers, educators, mental health professionals,
and community organizations better understand how people discuss and experience
climate-related concerns online.
""")

with st.expander("📚 Research & Educational Purpose"):
    st.markdown("""
    This application and its associated data, models, and findings are provided
    solely for research, educational, and informational purposes.

    ClimateLens is not intended to provide clinical advice, psychological
    assessment, diagnosis, or treatment recommendations.
    """)

with st.expander("🩺 No Clinical or Therapeutic Claims"):
    st.markdown("""
    The climate anxiety taxonomy, emotional mapping, and analytical outputs
    generated by ClimateLens are research tools only.

    They should not be used as substitutes for professional mental health
    services, clinical assessment, therapeutic intervention, or crisis support.

    Mental health professionals who use this platform should exercise their own
    professional judgment when interpreting or applying any insights.
    """)

with st.expander("📊 Data Limitations & Accuracy"):
    st.markdown("""
    The data and models are derived from publicly available social media
    conversations and computational analysis.

    Results may contain biases, inaccuracies, or limitations inherent in:

    - Social media data collection and processing
    - Automated topic modeling and sentiment analysis
    - Self-selected online populations
    - Temporal and demographic sampling limitations
    - Evolving language, slang, and online discourse

    Findings should be interpreted as research observations rather than
    definitive statements about individuals or populations.
    """)
